### ISSUE TITLE
Disabling animations throws exceptions and does not work

### ISSUE THREAD

**Issue by watermelonwolverine** [otigon/automated-jb2a-animations#489]
Steps to reproduce:

1. Open Settings
2. Set "Toggle Animations" to "OFF"
3. Click on "Save Changes" (need to do it twice, first time just throws exception)
4. Look at console
5. Reload 
6. Look at console
7. Make an attack/Use a spell

Result:
- Error logged in console after step 3:
```
foundry.js:5877 ReferenceError: socket is not defined
    at disableAnimations (autoAnimations.js:30:5)
    at Object.onChange (settings.js:50:17)
    at ClientSettings.set (foundry.js:2835:61)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at ClientSettings.settingsSet (force-client-settings.js:172:20)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:616:16)
    at 🎁ClientSettings.prototype.set#0 (libWrapper-wrapper.js:189:20)
    at SettingsConfig._updateObject (foundry.js:71192:27)
    at SettingsConfig._onSubmit (foundry.js:5874:18)
_onSubmit @ foundry.js:5877
```
- Error logged in console after step 5:
```
ReferenceError: socket is not defined
[Detected 1 package: autoanimations]
    at Object.fn (autoAnimations.js:129:9)
    at #call (foundry.js:724:20)
    at Hooks.callAll (foundry.js:681:17)
    at Object.fn (autoAnimations.js:496:11)
onError | @ | foundry.js:747
-- | -- | --
  | 🎁call_wrapped | @ | libWrapper-wrapper.js:507
  | 🎁Hooks.onError#lib-wrapper | @ | listeners.js:137
  | 🎁Hooks.onError#0 | @ | libWrapper-wrapper.js:187
  | #call | @ | foundry.js:728
  | callAll | @ | foundry.js:681
  | (anonymous) | @ | autoAnimations.js:496
  | await in (anonymous) (async) |   |  
  | #call | @ | foundry.js:724
  | callAll | @ | foundry.js:681
  | setupGame | @ | foundry.js:7854
  | await in setupGame (async) |   |  
  | _initializeGameView | @ | foundry.js:8899
  | _initializeView | @ | foundry.js:8875
  | initialize | @ | foundry.js:7727
  | await in initialize (async) |   |  
  | 🎁call_wrapped | @ | libWrapper-wrapper.js:507
  | 🎁libWrapperInit | @ | libWrapper-api.js:805
  | await in 🎁libWrapperInit (async) |   |  
  | 🎁Game.prototype.initialize#0 | @ | libWrapper-wrapper.js:187
  | window.addEventListener.once | @ | foundry.js:78838
```
- Animations still play

Expected result:
- No errors logged in console
- No animations played

**Comment by watermelonwolverine** [comment]
Generate Report Output:

```
Versions:
  Foundry: 10.286
  System: dnd5e version 2.0.3
User:
  Role: GAMEMASTER
Settings:
  Disable_Canvas: Disabled
  Max_FPS: 60
  Token_Drag_Vision: Disabled
  Performance_Mode: 2
  Token_Vision_Animation: Enabled
  Light_Source_Animation: Enabled
  Zoomed_Texture_Antialiasing: Enabled
  Animate_Roll_Tables: Enabled
Scene:
  Walls: 150
  Lights: 9
  Tokens: 11
  Tiles: undefined
  Sounds: 0
  Drawings: 0
  Notes: 0
  Dimensions: 19200 x 15360
  Background: undefined x undefined
  Foreground: undefined x undefined
WebGL:
  Context: WebGL2RenderingContext
  GL_Vendor: WebKit
  Renderer: WebKit WebGL
  Unmasked_Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 960M Direct3D11 vs_5_0 ps_5_0, D3D11)
  WebGL_Version: WebGL 2.0 (OpenGL ES 3.0 Chromium)
  MAX_TEXTURE_SIZE: 16384
  MAX_RENDERBUFFER: 16384
Database:
  Actors: 51
  Items: 3
  Scenes: 23
  Journals: 260
  Tables: 9
  Chat: 5
  Macros: 131
Data_Sizes:
  Actors: 1.76 MB
  Items: 6.7 KB
  Scenes: 358.35 KB
  Journals: 509.25 KB
  Tables: 10.15 KB
  Chat: 13.82 KB
  Macros: 198.65 KB
Browser:
  Platform: Win32
  Vendor: Google Inc.
  Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
Memory:
  Heap_Limit: 4 GB
  Heap_Total: 186.06 MB
  Heap_Used: 152.5 MB
Load:
  World_Size: 2.83 MB
  Scene_Size: 8.18 MB
Modules:
  Total: 61
  Enabled: 52
Active_Modules:
  about-time: About Time v10.0.1
  advanced-drawing-tools: Advanced Drawing Tools v2.0.2
  advanced-macros: Advanced Macros vv1.17
  autoanimations: Automated Animations v3.3.16
  betterroofs: Better Roofs v1.7
  combatbooster: Combat Booster: Turn Marker, Recent Actions and more v3.2
  compendium-folders: Compendium Folders v2.5.3
  dae: Dynamic effects using Active Effects v10.0.8
  ddb-importer: D&D Beyond Importer v3.1.11
  ddb-importer-compendiums: DDB Importer Compendiums v1.0.0
  debug-report: Debug Report Generator v0.1.5
  df-manual-rolls: DF Manual Rolls v2.3.1
  df-settings-clarity: DF Settings Clarity v3.2.1
  dfreds-convenient-effects: DFreds Convenient Effects v3.0.1
  dice-calculator: Dice Tray v1.5.2
  dice-so-nice: Dice So Nice! v4.6.2
  dice-tooltip: Dice Tooltip - DnD5e v2.3.1
  disable-mouse-wheel-sliders: Disable Mouse Wheel Control for Sliders v1.2.5
  force-client-controls: Force Client Controls v1.0.4
  force-client-settings: Force Client Settings v2.3.2
  forien-quest-log: Forien's Quest Log v0.7.11
  foundryvtt-simple-calendar: Simple Calendar v2.1.27
  fxmaster: FXMaster v3.5.0
  itemacro: Item Macro v1.8.0
  jb2a_patreon: JB2A - Patreon Complete Collection v0.4.7
  levels: Levels v3.2
  lib-changelogs: Changelogs & Conflicts v0.7.7
  lib-wrapper: libWrapper v1.12.10.0
  lmrtfy: Let Me Roll That For You! v3.0.3
  mcc: Module Compatibility Checker v1.3.2
  midi-qol: Midi QOL v10.0.12
  multi-token-edit: Mass Edit v1.19.0
  pause-icon: Alternative Pause Icon v1.0.2
  perfect-vision: Perfect Vision v4.0.24
  permission_viewer: Ownership Viewer v0.10.0
  popout: PopOut! v2.9
  select-tool-everywhere: Select tool everywhere v1.3.0
  sequencer: Sequencer v2.3.8
  shared-data: Shared Data v1.0.0
  smalltime: SmallTime v1.14.7
  smarttarget: Smart Target v0.9.3
  socketlib: socketlib v1.0.12
  tidy5e-sheet: Tidy5e Sheet v0.6.6
  times-up: Times Up v10.0.2
  token-animation-tools: Token Animation Tools v1.3.1.0
  token-attacher: Token Attacher v4.5.2
  token-chat-link: Token Chat Link v1.1.0
  token-variants: Token Variant Art v4.2.1
  token-z: Token Z v0.7.6
  tokenmagic: Token Magic FX v0.6.1.2
  vtta-tokenizer: Tokenizer v3.9.5
  wall-height: Wall Height v4.7.8
````

**Comment by otigon** [comment]
There will be an update to A-A in about 1-2 weeks that should resolve this. However this setting is changing to simply disable the A-A workflow. If you want animations to stop playing you should use the relevant Sequencer module settings

**Comment by otigon** [comment]
completed with A-A version 4.0.0
