### ISSUE TITLE
[BUG] - Item A-A Menu issue

### ISSUE THREAD

**Issue by Motara7** [otigon/automated-jb2a-animations#604]
**Describe the bug**
My AA Menu is blank. I can't make any changes to set up new animations. Although, all my existing animations still work.

**To Reproduce**
1. Open the AA menu.

**Expected behavior**
A usable menu opens up.

**Screenshots**
![AA Menu](https://user-images.githubusercontent.com/74425292/220771217-df32dfb7-4c9b-4bf7-bcdf-e7248456daac.JPG)

**Setup:**
 - Foundry Version: 10, 291
 - System Version: Pathfinder 1e 0.82.5
 - Sequencer Version: 2.411
 - Automated Animations version: 4.2.32
 - Hosting Location: linux box
 - Browser & version Chrome

**Active modules:**
 - Sequencer
 - socketlib
 - JB2A

**Additional context**
The first time I open the menu on an existing item, the console throws this error:
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'options')
    at $$self.$$.update (MeleeSwitch.svelte:29:44)
    at init (index.mjs:2006:8)
    at new MeleeSwitch (MeleeSwitch.svelte:36:146)
    at construct_svelte_component (index.mjs:839:12)
    at Array.create_else_block$4 (BuildMelee.svelte:41:41)
    at create_fragment$u (BuildMelee.svelte:25:26)
    at init (index.mjs:2010:37)
    at new BuildMelee (BuildMelee.svelte:11:22)
    at construct_svelte_component (index.mjs:839:12)
    at Object.p (CategoryList.svelte:44:43)

After I close the window, if I open the menu again, the window appears in the upper left corner of Foundry and cannot in interacted with or closed. This is the error:
foundry.js:747 TypeError: An error occurred while rendering ItemMenuApp 86. Cannot read properties of undefined (reading 'getAttribute')
    at attr (index.mjs:447:19)
    at Object.p (SectionButtons.svelte:59:25)
    at update (index.mjs:1191:36)
    at flush (index.mjs:1158:13)
    at init (index.mjs:2027:9)
    at new ItemAppShell (ItemAppShell.svelte:61:31)
    at loadSvelteConfig (loadSvelteConfig.js:73:22)
    at ItemMenuApp._injectHTML (SvelteApplication.js:468:29)
    at ItemMenuApp._render (foundry.js:5131:12)
    at async ItemMenuApp._render (SvelteApplication.js:856:7)
onError @ foundry.js:747

Followed by:
DevTools failed to load source map: Could not load content for http://192.168.1.151:30000/systems/pf1/rpg-awesome.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by Avitale34** [comment]
Having the same issue whenever I change the dropdown menu to "Presets"

**Comment by otigon** [comment]
it's a bug on the Item A-A menus, will be fixed in a few weeks when I get back to working on the module

**Comment by Motara7** [comment]
Is there a work around for this? Currently I cannot create new or edit existing animations because of this bug. Would it help if I uninstall/reinstall? If I do that, will I lose all the animations I've set up?

**Comment by otigon** [comment]
there is a fix in place for the next release, until then just use the Global menu

**Comment by otigon** [comment]
fixed on 4.2.40
